services:
  - type: web
    name: molecular-property-platform
    runtime: python
    plan: free
    branch: main

    buildCommand: |
      pip install -r requirements.txt
      pip install torch-scatter torch-sparse torch-cluster -f https://data.pyg.org/whl/torch-2.8.0+cpu.html

    startCommand: gunicorn app:app --workers 1 --threads 4 --timeout 300 --bind 0.0.0.0:$PORT

    healthCheckPath: /health

    envVars:
      - key: PYTHON_VERSION
        value: 3.9.25

      - key: FLASK_ENV
        value: production